import type { Metadata } from 'next'
import './globals.css'
import Header from "@/app/components/Header"
import Footer from '@/app/components/Footer';


export const metadata: Metadata = {
  title: 'FTR - FLIP THE RECORD | EN IDEELL KULTURELL TIDSKRIFT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="sv_SE">
      <body className="bg-white border-4 border-black font-sans">
        <Header/>
          {children}
          <Footer/>
      </body>
    </html>
  )
}
